package PlantFactory;

public enum PlantType {
    SUNFLOWERTYPE,
    CHERRYBOMBTYPE,
    JALAPENOTYPE,
    LILYPADTYPE,
    PEASHOOTERTYPE,
    REPEATERTYPE,
    SNOWPEATYPE,
    SQUASHTYPE,
    TALLNUTTYPE,
    WALLNUTTYPE
}
