package Picture;

public enum Picture {
    // Plant Card
    SUNFLOWERCARD,
    PEASHOOTERCARD,
    WALLNUTCARD,
    SNOWPEACARD,
    SQUASHCARD,
    LILY_PAD_SEEDCARD,
    CHERRYBOMBCARD,
    JALAPENOCARD,
    REPEATERCARD,
    TALLNUTCARD,

    // Zombie Card
    NORMALZOMBIECARD,
    CONEHEADZOMBIECARD,
    BUCKETHEADZOMBIECARD,
    SCREENDOORZOMBIECARD,
    FOOTBALLZOMBIECARD,
    POLEVAULTINGZOMBIECARD,
    DUCKYTUBEZOMBIECARD,
    DOLPHINERIDERZOMBIECARD,
    NEWSPAPERZOMBIECARD,
    IMPZOMBIECARD,

    // Background
    WELCOME,
    INVENTORY,
    GAMEDAY,
    GAMENIGHT,
    HELP,

    // Plant
    SUNFLOWER,
    PEASHOOTER,
    WALLNUT,
    SNOWPEA,
    SQUASH,
    LILY_PAD,
    CHERRYBOMB,
    JALAPENO,
    REPEATER,
    TALLNUT,

    // Welcoming Button
    STARTBUTTON,
    PLANTSBUTTON,
    ZOMBIESBUTTON,
    HELPBUTTON,
    EXITBUTTON,
    MENUBUTTON,

    // Help Button
    MENUBACKBUTTON,

    // Inventory Button
    SWAPBUTTON,
    DELETEBUTTON,
    CLEARBUTTON,
    NEXTBUTTON,
}
