package Picture;

import Zombie.NormalZombie;

public enum Picture {
    // Plant Card
    SUNFLOWERCARD,
    PEASHOOTERCARD,
    WALLNUTCARD,
    SNOWPEACARD,
    SQUASHCARD,
    LILY_PAD_SEEDCARD,
    CHERRYBOMBCARD,
    JALAPENOCARD,
    REPEATERCARD,
    TALLNUTCARD,

    // Zombie Card
    NORMALZOMBIECARD,
    CONEHEADZOMBIECARD,
    BUCKETHEADZOMBIECARD,
    SCREENDOORZOMBIECARD,
    FOOTBALLZOMBIECARD,
    POLEVAULTINGZOMBIECARD,
    DUCKYTUBEZOMBIECARD,
    DOLPHINERIDERZOMBIECARD,
    NEWSPAPERZOMBIECARD,
    IMPZOMBIECARD,

    // Plant
    SUNFLOWER,
    PEASHOOTER,
    WALLNUT,
    SNOWPEA,
    SQUASH,
    LILY_PAD,
    CHERRYBOMB,
    JALAPENO,
    REPEATER,
    TALLNUT,

    // Zombies
    NORMALZOMBIE,
    CONEHEADZOMBIE,
    BUCKETHEADZOMBIE,
    SCREENDOORZOMBIE,
    FOOTBALLZOMBIE,
    POLEVAULTINGZOMBIE,
    DUCKYTUBEZOMBIE,
    DOLPHINERIDERZOMBIE,
    NEWSPAPERZOMBIE,
    IMPZOMBIE,

    // Background
    WELCOME,
    PLANTSLISTBG,
    INVENTORY,
    GAMEDAY,
    GAMENIGHT,
    HELP,

    // Plants List
    SUNFLOWERLIST,
    PEASHOOTERLIST,
    REPEATERLIST,
    LILIPADLIST,
    TALLNUTLIST,
    SNOWPEALIST,
    WALLNUTLIST,
    CHERRYBOMBLIST,
    JALAPENOLIST,
    SQUASHLIST,

    // Welcoming Button
    STARTBUTTON,
    PLANTSBUTTON,
    ZOMBIESBUTTON,
    HELPBUTTON,
    EXITBUTTON,
    MENUBUTTON,

    // Plants List Button
    SUNFLOWERBUTTON,
    PEASHOOTERBUTTON,
    REPEATERBUTTON,
    LILIPADBUTTON,
    TALLNUTBUTTON,
    SNOWPEABUTTON,
    WALLNUTBUTTON,
    CHERRYBOMBBUTTON,
    JALAPENOBUTTON,
    SQUASHBUTTON,

    // Help Button
    MENUBACKBUTTON,

    // Inventory Button
    SWAPBUTTON,
    DELETEBUTTON,
    CLEARBUTTON,
    NEXTBUTTON,
}
