package Picture;

public enum Picture {
    // Plant Card
    SUNFLOWERCARD,
    PEASHOOTERCARD,
    WALLNUTCARD,
    SNOWPEACARD,
    SQUASHCARD,
    LILY_PAD_SEEDCARD,
    CHERRYBOMBCARD,
    JALAPENOCARD,
    NIGHTPEATERCARD,
    TALLNUTCARD,

    // Background
    WELCOME,
    INVENTORY,
    GAMEDAY,

    // Plant
    SUNFLOWER,
    PEASHOOTER,
    WALLNUT,
    SNOWPEA,
    SQUASH,
    LILY_PAD,
    CHERRYBOMB,
    JALAPENO,
    NIGHTPEATER,
    TALLNUT,

    // Welcoming Button
    STARTBUTTON,
    PLANTSBUTTON,
    ZOMBIESBUTTON,
    HELPBUTTON,
    EXITBUTTON,

    // Inventory Button
    SWAPBUTTON,
    DELETEBUTTON,
    CLEARBUTTON,
    NEXTBUTTON,

}
